
# Makefile for pipeline compilation

V10:
	g++ CIFAR_Backpipe_V10.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V10 -std=c++11
V11:
	g++ CIFAR_Backpipe_V11.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V11 -std=c++11
V12:
	g++ CIFAR_Backpipe_V12.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V12 -std=c++11
V13:
	g++ CIFAR_Backpipe_V13.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V13 -std=c++11
V14:
	g++ CIFAR_Backpipe_V14.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V14 -std=c++11
V15:
	g++ CIFAR_Backpipe_V15.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V15 -std=c++11
V16:
	g++ CIFAR_Backpipe_V16.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V16 -std=c++11
V17:
	g++ CIFAR_Backpipe_V17.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V17 -std=c++11
V18:
	g++ CIFAR_Backpipe_V18.cpp ../common/LoadCamModel.cpp ../common/MatrixOps.cpp -g -I ~/packages/halide/include/ -I ~/packages/halide/tools -L ~/packages/halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lm -o convert-V18 -std=c++11

